---
- name: restart alertmanager
  docker_container:
    name: "alertmanager"
    restart: true

- name: restart prometheus-tg-bot
  docker_container:
    name: "prometheus-bot"
    restart: true

- name: restart blackbox
  docker_container:
    name: "blackbox"
    restart: true
