---
- name: Create prometheus config dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "{{ prometheus_stack_prometheus_config_path }}"
    - "{{ prometheus_stack_prometheus_config_path }}/targets"
    - "{{ prometheus_stack_prometheus_config_path }}/alerts"
    - "{{ prometheus_stack_prometheus_data }}"

- name: Set prometheus config
  template:
    src: "prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_stack_prometheus_config_path }}/prometheus.yml"
    force: true
    mode: 0644
  register: prometheus_configuration
  notify: restart prometheus

- name: Add prometheus targets
  loop: "{{ prometheus_stack_prometheus_addition_target }}"
  template:
    src: "prometheus/target.yml.j2"
    dest: "{{ prometheus_stack_prometheus_config_path }}/targets/{{ item.ip }}.yml"
  vars:
    - target_ports: "{{ item.ports }}"
    - target_ip: "{{ item.ip }}"
    - target_labels: "{{ item.labels | default([]) }}"

- name: Configure alert rules
  template:
    src: "prometheus/alert.rules.j2"
    dest: "/etc/prometheus/alerts/ansible_managed.rules"

- name: Launch docker prometheus
  become: true
  docker_container:
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      {{ prometheus_stack_prometheus_additional_command_args }}
    image: prom/prometheus:{{ prometheus_stack_prometheus_version }}
    name: prometheus
    detach: true
    networks:
      - name: "{{ prometheus_stack_docker_network }}"
    recreate: "{{ prometheus_configuration.changed }}"
    published_ports:
      - "127.0.0.1:{{ prometheus_stack_prometheus_port }}:9090"
    restart_policy: always
    state: started
    volumes:
      - "{{ prometheus_stack_prometheus_config_path }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ prometheus_stack_prometheus_config_path }}/targets:/etc/prometheus/targets/:ro"
      - "{{ prometheus_stack_prometheus_config_path }}/alerts/:/etc/prometheus/alerts/:ro"
      - "{{ prometheus_stack_prometheus_data }}:/prometheus:rw"

- name: Check prometheus API works
  uri:
    url: http://localhost:{{ prometheus_stack_prometheus_port }}
    method: GET
    status_code: [200, 404, 405]
  retries: 15
  delay: 5
