---
- name: Create prometheus-tg-bot config dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_stack_prometheus_tg_bot_config_path }}"

- name: Set prometheus-tg-bot config
  template:
    src: "prometheus/telegram-bot.yml.j2"
    dest: "{{ prometheus_stack_prometheus_tg_bot_config_path }}/telegram-bot.yml"
    mode: 0644
  notify: restart prometheus-tg-bot

- name: Copy prometheus-tg-bot files
  copy:
    src: "prometheus/telegram-bot.tmpl"
    dest: "{{ prometheus_stack_prometheus_tg_bot_config_path }}/telegram-bot.tmpl"
    mode: 0644
  notify: restart prometheus-tg-bot

- name: Launch docker prometheus-tg-bot
  become: true
  docker_container:
    command: >
      /prometheus_bot
      -c /etc/prometheus/telegram-bot.yml
      -l 127.0.0.1:{{ prometheus_stack_prometheus_tg_bot_port }}
    image: mixbytes/prometheus-bot
    name: prometheus-bot
    detach: true
    networks:
      - name: "{{ prometheus_stack_docker_network }}"
    restart_policy: always
    state: started
    volumes:
      - "{{ prometheus_stack_prometheus_tg_bot_config_path }}/telegram-bot.yml:/etc/prometheus/telegram-bot.yml:ro"
      - "{{ prometheus_stack_prometheus_tg_bot_config_path }}/telegram-bot.tmpl:/etc/prometheus/telegram-bot.tmpl:ro"
